// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "graphqlEndpoint": "https://xxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
    "region": "us-west-2",
    "authenticationType": "API_KEY",
    "apiKey": "xxxxxx-xxxxxxx",
};

export default awsmobile;
