// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    // "aws_appsync_graphqlEndpoint": "https://xxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
    // "aws_appsync_region": "us-west-2",
    // "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    // "aws_appsync_apiKey": "xxx-xxxxxxx",
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:xxxxx-xxxx-xxxx-xxxx-xxxxxx',
    'aws_cognito_region': 'us-west-2',
    'aws_mobile_analytics_app_id': 'xxxxx',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'xxxxx-xxx-xxxx-xxxx-xxxx',
    'aws_project_name': 'proyecto_delta',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'proyectodelta-mobilehub-xxxxx',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-xxxxx',
    'aws_user_pools_web_client_id': 'xxxxxxxxx',
}

export default awsmobile;
